.TH NOWEB 1 "local 3/28/2001"
.SH NAME
noroots \- print roots of a noweb file
.SH SYNOPSIS
.B noroots
[file] ...
.SH DESCRIPTION
.I noroots
finds the roots of a
.I noweb
file: it prints the names of all code chunks that are defined but not used.
See
.IR noweb (1)
for an explanation of
the format of 
.I noweb
files.
.SH SEE ALSO
.IR noweb (1),
.IR notangle (1)
.SH VERSION
This man page is from 
.I noweb
version 2.11b.
.SH AUTHOR
Norman Ramsey, Harvard University.
Internet address \fBnr@eecs.harvard.edu\fP.
.br
Noweb home page at \fBhttp://www.eecs.harvard.edu/~nr/noweb\fP.

