#!/bin/sh
if [ $# -eq 0 ]; then set all install; fi  # "$@" breaks make for empty args
make CC="cc" CFLAGS=-DTEMPNAM LIBSRC=awk BIN=/usr/local/noweb/bin LIB=/usr/local/noweb/lib MAN=/usr/local/noweb/man TEXINPUTS=/usr/local/noweb/tex ELISP=$HOME/emacs "$@"
